apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels: 
    app: udagram-api-feed
spec:
  repllicas: 1
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadate:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        images: jazracherif/udagram-api-feed
        ports:
          containerPort: 80
